# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockstep < Formula
  desc "Keep your AI coding tools in lockstep across machines"
  homepage "https://github.com/doguyilmaz/lockstep"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doguyilmaz/lockstep/releases/download/v0.1.1/lockstep_0.1.1_darwin_amd64.tar.gz"
      sha256 "2df75a4657e8f0576ec3935aca27f89a0825b37d37cc931736197b687792deac"

      define_method(:install) do
        bin.install "lockstep"
        bin.install "lockstep-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doguyilmaz/lockstep/releases/download/v0.1.1/lockstep_0.1.1_darwin_arm64.tar.gz"
      sha256 "17852434683aa098d094faa1eed67c6645035fe73d052420654e1d62bbd3d886"

      define_method(:install) do
        bin.install "lockstep"
        bin.install "lockstep-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doguyilmaz/lockstep/releases/download/v0.1.1/lockstep_0.1.1_linux_amd64.tar.gz"
      sha256 "e51877c67c4b7c567c5f1934600f0fe6395c72ff0f44c13238ac0ce9d85295c4"
      define_method(:install) do
        bin.install "lockstep"
        bin.install "lockstep-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doguyilmaz/lockstep/releases/download/v0.1.1/lockstep_0.1.1_linux_arm64.tar.gz"
      sha256 "362a49504a1414b02d8bf77b808d335eca5ae9fa81583c524ef2ba099e7bd83d"
      define_method(:install) do
        bin.install "lockstep"
        bin.install "lockstep-server"
      end
    end
  end

  test do
    system "#{bin}/lockstep", "version"
  end
end
