# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockstep < Formula
  desc "Keep your AI coding tools in lockstep across machines"
  homepage "https://github.com/doguyilmaz/lockstep"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doguyilmaz/lockstep/releases/download/v0.1.0/lockstep_0.1.0_darwin_amd64.tar.gz"
      sha256 "0d25879c9743b95698f46bdd8ae003668ea498beddf478fd1d2234173cf40613"

      define_method(:install) do
        bin.install "lockstep"
        bin.install "lockstep-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doguyilmaz/lockstep/releases/download/v0.1.0/lockstep_0.1.0_darwin_arm64.tar.gz"
      sha256 "cfb6308054a9d7ae51613ddf54ce7e0b7f9f8c44ec1c76784985f0e6430bb6ac"

      define_method(:install) do
        bin.install "lockstep"
        bin.install "lockstep-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doguyilmaz/lockstep/releases/download/v0.1.0/lockstep_0.1.0_linux_amd64.tar.gz"
      sha256 "082125e362b026311f44dc445a608069420703a3420e40d897b1a02c671d479f"
      define_method(:install) do
        bin.install "lockstep"
        bin.install "lockstep-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doguyilmaz/lockstep/releases/download/v0.1.0/lockstep_0.1.0_linux_arm64.tar.gz"
      sha256 "4a1ebdb13006b0377720b9c78f8e26480acfbeff5c4b1688e0fc5a60e5dfb14f"
      define_method(:install) do
        bin.install "lockstep"
        bin.install "lockstep-server"
      end
    end
  end

  test do
    system "#{bin}/lockstep", "version"
  end
end
