# This file was generated by GoReleaser. DO NOT EDIT.
cask "aims" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "09c6c6ab89342cfb0dfc5efb5ff91b1fb86f275a80fc1353bd4913cd620d232b"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0465bd3ff1fffcb43d83b3e10087f4e610cd41cfe48cc7128b7d0c4e054dcc15"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "17450924df5b7e5be66fc4cf1bec4605d908eb29e1e41b64626fa3dc15c1902f"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2f71493d29c636dbdee08fafd0a7fe1f7ca1320067fdf449aab375cd7b467a08"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aims"
  desc "Several Claude Code and Codex accounts on one machine"
  homepage "https://doguyilmaz.github.io/aims/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aims"
  bash_completion "completions/aims.bash"
  fish_completion "completions/aims.fish"
  zsh_completion "completions/aims.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aims"]
    end
  end

  # No zap stanza required
end
