# This file was generated by GoReleaser. DO NOT EDIT.
cask "aims" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "cfb01279faeb8c4d2f5d4e256e114e55bcf55fb67c8be832493c606878263d49"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "148f70e9924a96ed45b3736ee01032cf641d748392615563e25a3be902f882d7"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "476e484e85e0de9f9436246ee5a7873f42312e57836c87f42fd8b461a294f93e"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "28dd27d61a30563c4aa9138d61c750bfac1ce306c7743318aad3e40ba2eb7140"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aims"
  desc "Several Claude Code and Codex accounts on one machine"
  homepage "https://doguyilmaz.github.io/aims/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aims"
  bash_completion "completions/aims.bash"
  fish_completion "completions/aims.fish"
  zsh_completion "completions/aims.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aims"]
    end
  end

  # No zap stanza required
end
