# This file was generated by GoReleaser. DO NOT EDIT.
cask "aims" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "4affbc47c7247dd1952d32506a2ec684c04ab4a7ad8e1c99f0f5be1ffe085720"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1f3330a5d400c7be79ce8568d1042cf8ba562c2352ccaa1eef4f4e947a3a20b"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b9d542d18b0ed3e8b5828ff40c9ff01223a9a7852f70b7f99ff541a0e4ba0697"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3dc267e4f71b558eb5df285f804eb6a2e62e4bd4ad5a8052d967bafc3245caf7"
      url "https://github.com/doguyilmaz/aims/releases/download/v#{version}/aims_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aims"
  desc "Several Claude Code and Codex accounts on one machine"
  homepage "https://doguyilmaz.github.io/aims/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aims"
  bash_completion "completions/aims.bash"
  fish_completion "completions/aims.fish"
  zsh_completion "completions/aims.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aims"]
    end
  end

  # No zap stanza required
end
