# Generated by scripts/update-tap.sh in doguyilmaz/battistics. DO NOT EDIT.
cask "battistics" do
  version "1.2.0"
  sha256 "d673437eb3454cc2273c130bb8d18b19bfd6c5a597ad44a425e9a48b27185af5"

  url "https://github.com/doguyilmaz/battistics/releases/download/v#{version}/Battistics-#{version}.dmg"
  name "Battistics"
  desc "Battery statistics for the Mac"
  homepage "https://github.com/doguyilmaz/battistics"

  livecheck do
    skip "Auto-generated on release."
  end

  auto_updates true
  depends_on macos: :sonoma

  app "Battistics.app"

  uninstall launchctl: "com.doguyilmaz.Battistics.PowerHelper",
            quit:      "com.doguyilmaz.Battistics"

  zap trash: [
    "~/Library/Application Support/Battistics",
    "~/Library/Caches/com.doguyilmaz.Battistics",
    "~/Library/Caches/com.dogukyilmaz.Battistics",
    "~/Library/HTTPStorages/com.doguyilmaz.Battistics",
    "~/Library/HTTPStorages/com.dogukyilmaz.Battistics",
    "~/Library/Preferences/com.doguyilmaz.Battistics.plist",
    "~/Library/Preferences/com.dogukyilmaz.Battistics.plist",
  ]
end
