# Generated by scripts/update-tap.sh in doguyilmaz/battistics. DO NOT EDIT.
cask "battistics" do
  version "1.4.0"
  sha256 "917c38173348156acea67cbfbcc86dd2d1572a8531ec0897b70eb0452a2a8c3b"

  url "https://github.com/doguyilmaz/battistics/releases/download/v#{version}/Battistics-#{version}.dmg"
  name "Battistics"
  desc "Battery statistics for the Mac"
  homepage "https://github.com/doguyilmaz/battistics"

  livecheck do
    skip "Auto-generated on release."
  end

  auto_updates true
  depends_on macos: :sonoma

  app "Battistics.app"

  uninstall launchctl: "com.doguyilmaz.Battistics.PowerHelper",
            quit:      "com.doguyilmaz.Battistics"

  zap trash: [
    "~/Library/Application Support/Battistics",
    "~/Library/Caches/com.doguyilmaz.Battistics",
    "~/Library/Caches/com.dogukyilmaz.Battistics",
    "~/Library/HTTPStorages/com.doguyilmaz.Battistics",
    "~/Library/HTTPStorages/com.dogukyilmaz.Battistics",
    "~/Library/Preferences/com.doguyilmaz.Battistics.plist",
    "~/Library/Preferences/com.dogukyilmaz.Battistics.plist",
  ]
end
