# This file was generated by GoReleaser. DO NOT EDIT.
cask "dothaven" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "f9f1b570ce05e90e781cfe7d218c6bd34044017aef47ca86efd5edb4f0bc2bbc"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c52e07943d37a845f8623d3bc1dc339eb64f44f9689dd0a3ddeafd25cfbe3631"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb623ed8fbde5a89438f75fac80c4f0a702b79d103eebb67d6851a0b7be4584f"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "09eeeee46ed9b03835edce150fc3e43349b0eab59fc0db91b73cf4256f00be28"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_linux_arm64.tar.gz"
    end
  end

  name "dothaven"
  desc "Discover, back up, and migrate your machine's dev config (chezmoi + age)"
  homepage "https://github.com/doguyilmaz/dothaven"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dothaven"

  # No zap stanza required

  caveats <<~EOS
    dothaven runs standalone. The encrypted-migration features
    (`dothaven chezmoi-export --apply`, `dothaven init`) also need chezmoi and age:
      brew install chezmoi age
  EOS
end
