# This file was generated by GoReleaser. DO NOT EDIT.
cask "dothaven" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "b27d7bffb301ffa0013e13a394a9387a134271cc11847f1e8ef3635c7c3e64ff"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4dc7553727c667f34cdedc33aba12cf11ac84f3b546c2c5f3b5833666eac8867"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "31dabb190c3256c890a72870e25a85946d46bd7717b254cb43fdae984907c7e8"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bf630d7b4223b4b0449573148bdbf0257fcab5f130b7d0002ab37b41fde8fbb"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_linux_arm64.tar.gz"
    end
  end

  name "dothaven"
  desc "Discover, back up, and migrate your machine's dev config (chezmoi + age)"
  homepage "https://github.com/doguyilmaz/dothaven"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dothaven"

  # No zap stanza required

  caveats <<~EOS
    dothaven runs standalone. The encrypted-migration features
    (`dothaven chezmoi-export --apply`, `dothaven init`) also need chezmoi and age:
      brew install chezmoi age
  EOS
end
