# This file was generated by GoReleaser. DO NOT EDIT.
cask "dothaven" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "373520c8bb905e51040883177f4b41c58f0b1750737803b20128f8ab8e90913a"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ce09efb8abd6392e05239d035b402425fb767671b234174b8ef7c3ab0fc0f26"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "54f1ed3352cd70e8fb45041b967914b886584166801a8e03ce7a47d1c6a886a8"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f931d08e9acbbb2d8c3238877c63cad511adc477860dd56bb6811b5568264e33"
      url "https://github.com/doguyilmaz/dothaven/releases/download/v#{version}/dothaven_linux_arm64.tar.gz"
    end
  end

  name "dothaven"
  desc "Discover, back up, and migrate your machine's dev config (chezmoi + age)"
  homepage "https://github.com/doguyilmaz/dothaven"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dothaven"

  # No zap stanza required

  caveats <<~EOS
    dothaven runs standalone. The encrypted-migration features
    (`dothaven chezmoi-export --apply`, `dothaven init`) also need chezmoi and age:
      brew install chezmoi age
  EOS
end
