# Generated by scripts/update-tap.sh in doguyilmaz/hafifpix. DO NOT EDIT.
cask "hafifpix" do
  version "1.3.1"
  sha256 "c3c6737a1afac3d4eaefd8602a24e9e219b93ef2cadd490dbd0e804f86f16fc5"

  url "https://github.com/doguyilmaz/hafifpix/releases/download/v#{version}/HafifPix-#{version}.dmg"
  name "HafifPix"
  desc "Native macOS image optimizer"
  homepage "https://github.com/doguyilmaz/hafifpix"

  livecheck do
    skip "Auto-generated on release."
  end

  auto_updates true
  depends_on macos: :sequoia

  app "HafifPix.app"
  binary "#{appdir}/HafifPix.app/Contents/Resources/bin/hafif"

  uninstall quit: "com.doguyilmaz.HafifPix"

  zap trash: [
    "~/Library/Caches/com.doguyilmaz.HafifPix",
    "~/Library/HTTPStorages/com.doguyilmaz.HafifPix",
    "~/Library/Preferences/com.doguyilmaz.HafifPix.plist",
  ]
end
