# typed: strict
# frozen_string_literal: true

# Generated by konvoy's release workflow. DO NOT EDIT.
cask "konvoy" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "5c06a02e84bdc25502cc143189494ad51424bdc1d2717c18e0b9497a26fec29e"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "45277c138c3b810217e58f1f1de71369fd6e9b08408f64e8c390d12942512869"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4a60cd19b24d47a0f6a3ff803fed495a0f0f03a4236123a6f67243078e927bdc"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7317ad3f7b616debfdb7db1e177f6116c150ad19ad6826edfdb0c709c4cb7b19"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_linux_amd64.tar.gz"
    end
  end

  name "konvoy"
  desc "One session across Claude Code, Codex, Kiro CLI and opencode"
  homepage "https://github.com/doguyilmaz/konvoy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "konvoy"

  caveats <<~EOS
    konvoy drives the agent CLIs you already have. Install whichever you use:
      claude, codex, kiro-cli, opencode
    Each authenticates itself; konvoy never handles credentials.
  EOS
end
