# typed: strict
# frozen_string_literal: true

# Generated by konvoy's release workflow. DO NOT EDIT.
cask "konvoy" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "07b527e52a1af0ba03a6a9d5c828e2cd8da2e8d05ec75febf35ba3930f0bd20d"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "41102b5cff6888f163856d3181e95c725ad6933d1d0f78275145e89f48dcf3e6"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e26fefac4fdd734dbc3fba8e47cab697f480b40f45486d8ee46240dd64a50d25"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "40df95950ae7d5e8cfa0375225a5cb4866c6bf0e7f4c20d2359a267a2170137c"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_linux_amd64.tar.gz"
    end
  end

  name "konvoy"
  desc "One session across Claude Code, Codex, Kiro CLI and opencode"
  homepage "https://github.com/doguyilmaz/konvoy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "konvoy"

  caveats <<~EOS
    konvoy drives the agent CLIs you already have. Install whichever you use:
      claude, codex, kiro-cli, opencode
    Each authenticates itself; konvoy never handles credentials.
  EOS
end
