# typed: strict
# frozen_string_literal: true

# Generated by konvoy's release workflow. DO NOT EDIT.
cask "konvoy" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "3707f7a6ac72819c336b4ffac33b56947bce416cfed0fef736f5c2dbfc2b667a"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "00eb15a4f9f888c361098d2bfee9a0f9dfb7532de82d124d6db3409f23edffba"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "747a295ab1ff0dbae2a0412ab3921bdfc0851ebde072a0662980bd2280aefe95"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "010b4055b0761ac32b1e4588ef087de1c85be033711b370c1fc5f59518e9042b"
      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/konvoy_linux_amd64.tar.gz"
    end
  end

  name "konvoy"
  desc "One session across Claude Code, Codex, Kiro CLI and opencode"
  homepage "https://github.com/doguyilmaz/konvoy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "konvoy"

  caveats <<~EOS
    konvoy drives the agent CLIs you already have. Install whichever you use:
      claude, codex, kiro-cli, opencode
    Each authenticates itself; konvoy never handles credentials.
  EOS
end
